# Generated by Django 4.2 on 2024-05-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_name', max_length=150, unique=True, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
