# Generated by Django 4.2 on 2024-05-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publication_sign',
            field=models.BooleanField(default=False),
        ),
    ]
