# Generated by Django 5.0.6 on 2024-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailing_end_date_alter_mailing_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
