# Generated by Django 4.2 on 2024-05-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mailings', '0004_alter_mailing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='can_block',
            field=models.ManyToManyField(related_name='can_block_users', to='auth.group'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='can_disable',
            field=models.ManyToManyField(related_name='can_disable_mailings', to='auth.group'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='can_view',
            field=models.ManyToManyField(related_name='can_view_mailings', to='auth.group'),
        ),
    ]
