# Generated by Django 4.2 on 2024-05-31 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailings', '0006_alter_mailing_options_remove_mailing_can_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
